/** update  RSS data*/
export const ADD_RSS_DATA = 'ADD_RSS_DATA';
export const DELETE_RSS_DATA = 'DELETE_RSS_DATA';
export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';
export const SAVE_STATE_TO_LOCAL_STORAGE = 'SAVE_STATE_TO_LOCAL_STORAGE';
export const INITIALIZE_FROM_LOCAL_STORAGE = 'INITIALIZE_FROM_LOCAL_STORAGE';